language: go
go:
  - "1.9.x"
  - "1.10.x"
install: make install-ci
sudo: required
dist: trusty
env:
  global:
    - TEST_TIMEOUT_SCALE=20
    - PACKAGE=github.com/m3db/m3msg
  matrix:
    - MAKE_TARGET="test-ci-unit"
    - MAKE_TARGET="metalint"
script: "make $MAKE_TARGET"
