version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
      - "2379-2380"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
      - "0.0.0.0:2379-2380:2379-2380"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    depends_on:
      - etcd
  coordinator01:
    expose:
      - "7201"
      - "7203"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./:/etc/m3coordinator/"
    depends_on:
      - etcd
networks:
  backend: null
