language: go
go:
  - 1.8.3
  - 1.9.2
install: make install-ci
env:
  global:
    - TEST_TIMEOUT_SCALE=20 # Set higher timeouts for Travis
    - PACKAGE=github.com/$TRAVIS_REPO_SLUG
sudo: required
dist: trusty
script:
 - make all
