"coordinator":
  "listenAddress": "0.0.0.0:7201"
  "local":
    "namespaces":
    - "namespace": "default"
      "retention": "48h"
      "type": "unaggregated"
  "logging":
    "level": "info"
  "metrics":
    "extended": "none"
    "prometheus":
      "handlerPath": "/metrics"
      "listenAddress": "0.0.0.0:7203"
    "samplingRate": 1
    "sanitization": "prometheus"
    "scope":
      "prefix": "coordinator"
  "tagOptions":
    "idScheme": "quoted"
"db":
  "cache":
    "postingsList":
      "size": 262144
    "series":
      "policy": "lru"
  "client":
    "readConsistencyLevel": "unstrict_majority"
    "writeConsistencyLevel": "majority"
  "clusterListenAddress": "0.0.0.0:9001"
  "commitlog":
    "flushEvery": "1s"
    "flushMaxBytes": 524288
    "queue":
      "calculationType": "fixed"
      "size": 2097152
  "config":
    "seedNodes":
      "initialCluster":
      - "endpoint": "http://host_ip1:2380"
        "hostID": "host_name1"
      - "endpoint": "http://host_ip2:2380"
        "hostID": "host_name2"
      - "endpoint": "http://host_ip3:2380"
        "hostID": "host_name3"
    "service":
      "cacheDir": "/var/lib/m3kv"
      "env": "default_env"
      "etcdClusters":
      - "endpoints":
        - "http://host_ip1:2379"
        - "http://host_ip2:2379"
        - "http://host_ip3:2379"
        "zone": "embedded"
      "service": "m3db"
      "zone": "embedded"
  "debugListenAddress": "0.0.0.0:9004"
  "fs":
    "filePathPrefix": "/var/lib/m3db"
  "gcPercentage": 100
  "hostID":
    "resolver": "hostname"
  "httpClusterListenAddress": "0.0.0.0:9003"
  "httpNodeListenAddress": "0.0.0.0:9002"
  "listenAddress": "0.0.0.0:9000"
  "logging":
    "level": "info"
  "metrics":
    "extended": "detailed"
    "prometheus":
      "handlerPath": "/metrics"
    "samplingRate": 1
    "sanitization": "prometheus"
  "writeNewSeriesAsync": true
  "writeNewSeriesBackoffDuration": "2ms"
