version: "3.5"
services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - backend
  dbnode01:
    expose:
      - "9000-9004"
      - "7201"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
      - "0.0.0.0:7201:7201"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    depends_on:
      - etcd
  m3coordinator01:
    expose:
      - "7202"
      - "7203"
      - "7204"
    ports:
      - "0.0.0.0:7202:7202"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7204:7204"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./m3coordinator.yml:/etc/m3coordinator/m3coordinator.yml"
    depends_on:
      - etcd
  m3aggregator01:
    expose:
      - "6001"
    ports:
      - "127.0.0.1:6001:6001"
    networks:
      - backend
    environment:
      - M3AGGREGATOR_HOST_ID=m3aggregator01
    image: "m3aggregator_integration:${REVISION}"
    volumes:
      - "./m3aggregator.yml:/etc/m3aggregator/m3aggregator.yml"
    depends_on:
      - etcd
  m3aggregator02:
    networks:
      - backend
    environment:
      - M3AGGREGATOR_HOST_ID=m3aggregator02
    image: "m3aggregator_integration:${REVISION}"
    volumes:
      - "./m3aggregator.yml:/etc/m3aggregator/m3aggregator.yml"
    depends_on:
      - etcd
networks:
  backend: null
