version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
      - "2379-2380"
    ports:
      - "0.0.0.0:9012:9002"
      - "0.0.0.0:9013:9003"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    environment:
      - M3DB_HOST_ID=m3db_local_1
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
    depends_on:
      - etcd
  dbnode02:
    expose:
      - "9000-9004"
      - "2379-2380"
    ports:
      - "0.0.0.0:9022:9002"
      - "0.0.0.0:9023:9003"
    networks:
      - backend
    image: "m3dbnode_integration:${REVISION}"
    environment:
      - M3DB_HOST_ID=m3db_local_2
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
    depends_on:
      - etcd
  coordinator01:
    expose:
      - "7201"
      - "7203"
      - "7204"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7204:7204"
    networks:
      - backend
    image: "m3coordinator_integration:${REVISION}"
    volumes:
      - "./:/etc/m3coordinator/"
    depends_on:
      - etcd
networks:
  backend: null
